# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjMRwXimPl2UaIT1DMef7juYWhH2wAx-
"""

import streamlit as st
st.title("Image Classification with Google's Teachable Machine")
st.header("COVID-19 Classification via Ct imsges")
st.text("Upload an Image for classification as covid or non-covid")